# Generated by Django 5.0.3 on 2024-04-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_image'),
        ('main', '0005_profile'),
    ]

    operations = [
    ]
